name: Python CI/CD Merge Pipeline for Live

on:
  pull_request:
    types: [closed]
    branches:
      - 'master'

env:
  AZURE_FUNCTIONAPP_NAME: ${{ vars.AZURE_FUNCTION_APP_NAME }}
  AZ_FN_APP_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_889F1DDFFEFA43718D7757FE2F1925DF }}
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.11.2]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        
    # Cache Python dependencies to speed up builds
    - name: Cache Python dependencies
      uses: actions/cache@v4.0.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with ruff
      run: |
        pip install ruff
        ruff .

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: |
          release.zip
          !venv/

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'fa-data-ingestion'
          slot-name: 'production'
          package: $AZURE_FUNCTIONAPP_PACKAGE_PATH
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          publish-profile: $AZ_FN_APP_PUBLISH_PROFILE
